sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g codecov
  - npm install -g webpack
  - npm install

script:
#  - npm test
#  - npm run build

after_success:
  - npm run codecov

branches:
  only:
    - develop

notifications:
  email:
    on_failure: change
    on_success: change
